# Generated by Django 3.2.7 on 2021-09-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='query',
            field=models.TextField(max_length=500),
        ),
    ]
